/* Copyright 2019-2022,2026 NXP
 * 
 * NXP Proprietary. This software is owned or controlled by NXP and may only
 * be used strictly in accordance with the applicable license terms.  By
 * expressly accepting such terms or by downloading, installing, activating
 * and/or otherwise using the software, you are agreeing that you have read,
 * and that you agree to comply with and are bound by, such license terms.  If
 * you do not agree to be bound by the applicable license terms, then you may
 * not retain, install, activate or otherwise use the software.
 * 
 */

#ifndef UWBIOTVER_STR_VERSION_INFO_H_INCLUDED
#define UWBIOTVER_STR_VERSION_INFO_H_INCLUDED


/* clang-format off */
#define UWBIOTVER_STR_PROD_NAME          "UWBIOT"
#define UWBIOTVER_STR_VER_STRING_NUM     "v05.10.08"
#define UWBIOTVER_STR_PROD_NAME_VER_FULL "UWBIOT_v05.10.08"
#define UWBIOTVER_STR_VER_MAJOR          (5u)
#define UWBIOTVER_STR_VER_MINOR          (10u)
#define UWBIOTVER_STR_VER_DEV            (8u)

/* v05.10 = 50010u */
#define UWBIOTVER_STR_VER_MAJOR_MINOR ( 0         \
    + (UWBIOTVER_STR_VER_MAJOR * 10000u)          \
    + (UWBIOTVER_STR_VER_MINOR))

/* v05.10.08 = 500100008ULL */
#define UWBIOTVER_STR_VER_MAJOR_MINOR_DEV ( 0          \
    + (UWBIOTVER_STR_VER_MAJOR * 10000ULL*10000ULL)    \
    + (UWBIOTVER_STR_VER_MINOR * 10000ULL)             \
    + (UWBIOTVER_STR_VER_DEV))

/* clang-format on */


/* Version Information:
 * Generated by:
 *     version_update.py (v2022.03.22_00)
 * 
 * Do not edit this file. Update:
 *     ../version_info.txt instead.
 */

#endif /* UWBIOTVER_STR_VERSION_INFO_H_INCLUDED */
